### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by bettercallazamat**
In this milestone we displayed prompts for users, collect user input and only mock the basic flow of the game.
We made sure that we can run our game and play with the basic flow.
We added game logic in order to make the game playable in main(win, draw) scenarios that we will move to Classes in the next milestone.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
## Hi team ! Very nice project! :wave: 

# Status: [changes required]

You have made tremendous progress in this project. However, we need to fix a few major features before merging.


* [ ] A loop is needed in this game (recommended is while but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [ ] Inside the loop, all actions should be repeated for each move
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

while


*The final point of this milestone is to make sure that you thought about all the actions needed to play Tic Tac Toe from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by idgm5** [comment]
Hello @Anna-Myzukina,

Thank you for reviewing our code! :)

I think there's a misunderstanding with the current branch you reviewed, are you sure that you're in the user_interface branch? 

We have a working prototype of the game with loops and win/draw scenarios, that you can play directly by running the following command inside of bin directory:

`ruby main.rb`

image

**Comment by Anna-Myzukina** [comment]
## Hi team ! Very nice project! :wave: 

# You did a great job, approved  :+1:

### Go and merge to develop.
`Goodluck in your next milestone Happy coding ` <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by Anna-Myzukina — APPROVED** [review]
Approved

**Pull request merged**
